[[navbar]]
  identifier = "github"
  name = "Github"
  url = "https://github.com/garado"
  weight = 10

[[navbar]]
  identifier = "linkedin"
  name = "LinkedIn"
  url = "https://linkedin.com/in/garado"
  weight = 20

[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts"
  weight = 30

[[navbar]]
  identifier = "outside"
  name = "Outside"
  url = "/outside"
  weight = 50
